### PR TITLE
Supports installation via `pip`; fixes relative import bug

### PR DESCRIPTION
**Pull request by tvwenger**
Fixes issues discussed in https://github.com/PrincetonUniversity/astro-tigress/issues/4

The details in `setup.py` (author contact, license) should be updated. Or, alternatively, a `pyproject.toml` file.

### CODE REVIEW

**Comment by tvwenger** [comment]
The bug is a duplicate of https://github.com/PrincetonUniversity/astro-tigress/pull/3

**Comment by changgoo** [comment]
Hey Trey! Thanks for the PR. I at some point changed from poetry to pip for packaging (`pyproject.toml` is in the `old_master` branch) but didn't made proper updates in the documentation. As I recently had a newborn, I will be a bit slow in testing and updating. But, as it looks like a solution, I will merge it for now. Can you revised `install.md` to conform this PR?

**Comment by tvwenger** [comment]
@changgoo done!

**Comment by changgoo** [comment]
Thanks a lot! I will clean up for linting and deployment later.

**Pull request merged**
